/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Student.Student;
import java.time.LocalDate;
import javafx.util.converter.LocalDateStringConverter;
import javax.swing.JOptionPane;
import model.StudentDB;

/**
 *
 * @author Laptop88
 */
public class AddNewStudent extends javax.swing.JPanel {

    /**
     * Creates new form AddNewStudent
     */
    public AddNewStudent() {    
        this.setBounds(4000, 1000, 5000, 5000);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        add = new javax.swing.JButton();
        centerPane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        codetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gendertxt = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Registration");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        reset.setText("Reset");
        jPanel1.add(reset);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        centerPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        centerPane.setLayout(new java.awt.GridLayout(4, 4, 10, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Student Code");
        centerPane.add(jLabel6);

        codetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codetxtActionPerformed(evt);
            }
        });
        centerPane.add(codetxt);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Student Name");
        centerPane.add(jLabel7);
        centerPane.add(nametxt);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Date Of Birth");
        centerPane.add(jLabel8);
        centerPane.add(datetxt);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Gender");
        centerPane.add(jLabel9);
        centerPane.add(gendertxt);

        add(centerPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void codetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codetxtActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:       
        String code = new String(codetxt.getText());      
        String name = new String(nametxt.getText());
        String dob = new String(datetxt.getText());
        int gender = new Integer(gendertxt.getText());
        Student s = new Student(code, name, dob, gender);
        
        boolean u = StudentDB.addNewStudent(code, name, dob,gender);        
            if(u==false){
                    JOptionPane.showMessageDialog(this, "Erroll!!!");}
            else{
                JOptionPane.showMessageDialog(this, "Add Success!!!");       
    }    
    }//GEN-LAST:event_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JPanel centerPane;
    private javax.swing.JTextField codetxt;
    private javax.swing.JTextField datetxt;
    private javax.swing.JTextField gendertxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
