/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Course;

import static Course.DatabaseInfo.*;
import java.sql.*;

/**
 *
 * @author Admin
 */
public class Display extends javax.swing.JPanel {

    /**
     * Creates new form Dplay
     */
    public Display() throws ClassNotFoundException {
        initComponents();
        try {
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL, userDB, passDB);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select * from Course order by Credit ");
            while (rs.next()) {
                String id = rs.getString(1);
                String nameCourse = rs.getString(2);
                int cre = rs.getInt(3);
                jTextArea1.setText(jTextArea1.getText()+ "\n" + id + "   |   " + nameCourse + "   |   " + cre);
                jTextArea1.setEditable(false);
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println("Error!");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List of all course(Oderbycredit)");
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 50));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
