/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caculator;

/**
 *
 * @author macbookpro
 */
import java.util.Arrays;
import java.util.Scanner;
import java.util.Stack;

public class Calcu extends javax.swing.JFrame
{
    String s ="";
    /**
     * Creates new form Calculator
     */
    
    public Calcu()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Screen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        chia = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        nhan = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        cong = new javax.swing.JButton();
        cham = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        tru = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        bang = new javax.swing.JButton();
        Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 345));

        jPanel1.setLayout(new java.awt.BorderLayout());

        Screen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Screen.setMinimumSize(new java.awt.Dimension(10, 20));
        Screen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreenActionPerformed(evt);
            }
        });
        jPanel1.add(Screen, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CALCULATOR");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(4, 4));

        b7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel3.add(b7);

        b8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel3.add(b8);

        b9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel3.add(b9);

        chia.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        chia.setText("/");
        chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiaActionPerformed(evt);
            }
        });
        jPanel3.add(chia);

        b4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel3.add(b4);

        b5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel3.add(b5);

        b6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel3.add(b6);

        nhan.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        nhan.setText("*");
        nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanActionPerformed(evt);
            }
        });
        jPanel3.add(nhan);

        b1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel3.add(b1);

        b2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel3.add(b2);

        b3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel3.add(b3);

        cong.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        cong.setText("+");
        cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congActionPerformed(evt);
            }
        });
        jPanel3.add(cong);

        cham.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        cham.setText(".");
        cham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamActionPerformed(evt);
            }
        });
        jPanel3.add(cham);

        b0.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel3.add(b0);

        clear.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear);

        tru.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        tru.setText("-");
        tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truActionPerformed(evt);
            }
        });
        jPanel3.add(tru);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        bang.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        bang.setText("=");
        bang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangActionPerformed(evt);
            }
        });
        jPanel4.add(bang);

        Delete.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel4.add(Delete);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        s = s + 7;
        Screen.setText(s);
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        s = s + 8;
        Screen.setText(s);
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        s = s + 9;
        Screen.setText(s);
    }//GEN-LAST:event_b9ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        s = s + 6;
        Screen.setText(s);
    }//GEN-LAST:event_b6ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        s = s + 5;
        Screen.setText(s);
    }//GEN-LAST:event_b5ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        s = s + 4;
        Screen.setText(s);
    }//GEN-LAST:event_b4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        s = s + 1;
        Screen.setText(s);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        s = s + 2;
        Screen.setText(s);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        s = s + 3;
        Screen.setText(s);
    }//GEN-LAST:event_b3ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        s = "";
        Screen.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void chiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiaActionPerformed
        s = s + "/";
        Screen.setText(s);
    }//GEN-LAST:event_chiaActionPerformed

    private void nhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanActionPerformed
        s = s + "*";
        Screen.setText(s);
    }//GEN-LAST:event_nhanActionPerformed

    private void congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congActionPerformed
        s = s + "+";
        Screen.setText(s);
    }//GEN-LAST:event_congActionPerformed

    private void truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truActionPerformed
        s = s + "-";
        Screen.setText(s);
    }//GEN-LAST:event_truActionPerformed

    private void chamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamActionPerformed
        s = s + ".";
        Screen.setText(s);
    }//GEN-LAST:event_chamActionPerformed

    private void bangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangActionPerformed
        String sm = "", elementMath[] = null, e[];
        Calcu bl = new Calcu();
        elementMath = bl.processString(s);
        e = bl.postfix(elementMath); 
        sm = sm + bl.valueMath(e);
        Screen.setText(sm);
        s=sm;
        
    }//GEN-LAST:event_bangActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if(!s.isEmpty())
            s = s.substring(0, s.length()- 1);

        Screen.setText(s);
    }//GEN-LAST:event_DeleteActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        s = s + 0;
        Screen.setText(s);
    }//GEN-LAST:event_b0ActionPerformed

    private void ScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScreenActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    public int priority(char c)
    {
        if (c == '+' || c == '-') {
            return 1;
        }
        else if (c == '*' || c == '/')
        {
            return 2;
        }
        else
        {
            return 0;
        }
    }

    public boolean isOperator(char c)
    {
        char op[] = {'+', '-', '*', '/', ')', '('};
        Arrays.sort(op);
        if (Arrays.binarySearch(op, c) > -1)
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    public String[] processString(String sm)
    { 
        String s1 = "", elementMath[] = null;
        Calcu bl = new Calcu();
        sm = sm.trim();
        sm = sm.replaceAll("\\s+", " ");
        for (int i = 0; i < sm.length(); i++)
        {
            char c = sm.charAt(i);
            if (!bl.isOperator(c))
            {
                s1 = s1 + c;
            }
            else
            {
                s1 = s1 + " " + c + " ";
            }
        }
        s1 = s1.trim();
        s1 = s1.replaceAll("\\s+", " "); 
        elementMath = s1.split(" ");
        return elementMath;
    }

    public String[] postfix(String[] elementMath)
    {
        Calcu bl = new Calcu();
        String s1 = "", E[];
        Stack<String> S = new Stack<String>();
        for (int i = 0; i < elementMath.length; i++)
        { 
            char c = elementMath[i].charAt(0); 

            if (!bl.isOperator(c))
            {
                s1 = s1 + " " + elementMath[i];
            }
            else
            {       
                if (c == '(')
                {
                    S.push(elementMath[i]); 
                }
                else
                {
                    if (c == ')')
                    {        
                        char c1; 
                        do
                        {
                            c1 = S.peek().charAt(0); 
                            if (c1 != '(')
                            {
                                s1 = s1 + " " + S.peek();   
                            }
                            S.pop();
                        }
                        while (c1 != '(');
                    }
                    else
                    {
                        while (!S.isEmpty() && bl.priority(S.peek().charAt(0)) >= bl.priority(c))
                        {
                            s1 = s1 + " " + S.peek();
                            S.pop();
                        }
                        S.push(elementMath[i]);
                    }
                }
            }
        }
        while (!S.isEmpty())
        { 
            s1 = s1 + " " + S.peek();
            S.pop();
        }
        E = s1.split(" ");  
        return E;
    }
    
    public Double valueMath(String[] elementMath)
    {
        Stack<Double> s = new Stack<>();
        for (int i=1; i<elementMath.length; i++)
        {
            try
            {
                double d = Double.parseDouble(elementMath[i].trim());
                s.push(d);
            }catch(NumberFormatException e)
            {
                double num = 0f;
                double num1 = s.pop();
                double num2 = s.pop();
                switch (elementMath[i])
                {
                    case "+" : num = num2 + num1; break;
                    case "-" : num = num2 - num1; break;
                    case "*" : num = num2 * num1; break;
                    case "/" : num = num2 / num1; break;
                }
                s.push(num);
            }
        }
    return s.pop();
    }
    
    
    
    
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcu().setVisible(true);
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Screen;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bang;
    private javax.swing.JButton cham;
    private javax.swing.JButton chia;
    private javax.swing.JButton clear;
    private javax.swing.JButton cong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton nhan;
    private javax.swing.JButton tru;
    // End of variables declaration//GEN-END:variables
}
