/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test2;

/**
 *
 * @author OS
 */
public class XuLi extends javax.swing.JFrame {

    /**
     * Creates new form XuLi
     */
    public XuLi() {       
        initComponents();
        this.setTitle("Xử lý chuỗi");
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        okbt = new javax.swing.JButton();
        resetbt = new javax.swing.JButton();
        exitbt = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        nhaptxt = new javax.swing.JTextField();
        chuoihoatxt = new javax.swing.JTextField();
        chuoithuongtxt = new javax.swing.JTextField();
        hoathuongtxt = new javax.swing.JTextField();
        sotutxt = new javax.swing.JTextField();
        cacnguyenamtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 100));
        setMinimumSize(new java.awt.Dimension(400, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Xứ Lí Chuỗi");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(6, 1));

        jLabel3.setText("Nhập chuỗi");
        jPanel2.add(jLabel3);

        jLabel4.setText("Chuỗi hoa");
        jPanel2.add(jLabel4);

        jLabel5.setText("Chuỗi thường");
        jPanel2.add(jLabel5);

        jLabel6.setText("Hoa thường");
        jPanel2.add(jLabel6);

        jLabel7.setText("Số từ");
        jPanel2.add(jLabel7);

        jLabel8.setText("Các nguyên âm");
        jPanel2.add(jLabel8);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel6.setLayout(new java.awt.GridLayout(3, 1));

        okbt.setText("OK");
        okbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtActionPerformed(evt);
            }
        });
        jPanel6.add(okbt);

        resetbt.setText("Reset");
        resetbt.setToolTipText("");
        resetbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtActionPerformed(evt);
            }
        });
        jPanel6.add(resetbt);

        exitbt.setText("Exit");
        exitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtActionPerformed(evt);
            }
        });
        jPanel6.add(exitbt);

        jPanel1.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel3.setLayout(new java.awt.GridLayout(6, 1));
        jPanel3.add(nhaptxt);

        chuoihoatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuoihoatxtActionPerformed(evt);
            }
        });
        jPanel3.add(chuoihoatxt);
        jPanel3.add(chuoithuongtxt);
        jPanel3.add(hoathuongtxt);
        jPanel3.add(sotutxt);
        jPanel3.add(cacnguyenamtxt);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public static String chuoihoa(String st) {
        String result = "";
        for (int i = 0; i < st.length(); i++) {
            char tmp = st.charAt(i);
            if ((int) st.charAt(i) >= 97 && (int) st.charAt(i) <= 122) {
                tmp = toUpper(st.charAt(i));
            }
            result = result + tmp;
        }
        return result;
    }

    public static String chuoithuong(String st) {
        String result = "";
        for (int i = 0; i < st.length(); i++) {
            char tmp = st.charAt(i);
            if ((int) st.charAt(i) >= 65 && (int) st.charAt(i) <= 90) {
                tmp = toLower(st.charAt(i));
            }
            result = result + tmp;
        }
        return result;
    }

    public static String hoathuong(String st) {
        String result = "";
        for (int i = 0; i < st.length(); i++) {
            char tmp = st.charAt(i);
            if ((int) st.charAt(i) >= 65 && (int) st.charAt(i) <= 90) {
                tmp = toLower(st.charAt(i));
            }
            if ((int) st.charAt(i) >= 97 && (int) st.charAt(i) <= 122) {
                tmp = toUpper(st.charAt(i));
            }
            result = result + tmp;
        }
        return result;
    }

    public static String soTu(String st) {
        if (st.equals("")) {
            return String.valueOf(0);
        }
        int d = 1;
        boolean check = false;
        for (int i = 0; i < st.length(); i++) {
            if (st.charAt(i) == ' ') {
                check = true;
            }
            if (check && st.charAt(i) != ' ') {
                check = false;
                d++;
            }
        }
        return String.valueOf(d);
    }

    public static String nguyenam(String st) {     
        String result = "";
        
        for (int i = 0; i < st.length(); i++) {
            if (st.charAt(i) == 'U' && st.charAt(i) == 'u') {
                result = result + st.charAt(i);
            }
            if (st.charAt(i) == 'E' && st.charAt(i) == 'e') {
                result = result + st.charAt(i);
            }
             if (st.charAt(i) == 'O' && st.charAt(i) == 'o') {
                result = result + st.charAt(i);
            }
             if (st.charAt(i) == 'A' && st.charAt(i) == 'a') {
                result = result + st.charAt(i);
            }
             if (st.charAt(i) == 'I' && st.charAt(i) == 'i') {
                result = result + st.charAt(i);
            }             
        }
        return result;
    }

    public static char toUpper(char c) {
        int tmp = (int) c;
        tmp = tmp - 32;
        return (char) tmp;
    }

    public static char toLower(char c) {
        int tmp = (int) c;
        tmp = tmp + 32;
        return (char) tmp;
    }

    private void chuoihoatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuoihoatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chuoihoatxtActionPerformed

    private void resetbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtActionPerformed
        // TODO add your handling code here:
        nhaptxt.setText("");
        chuoihoatxt.setText("");
        chuoithuongtxt.setText("");
        hoathuongtxt.setText("");
        sotutxt.setText("");
        cacnguyenamtxt.setText("");
    }//GEN-LAST:event_resetbtActionPerformed

    private void exitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbtActionPerformed

    private void okbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbtActionPerformed
        // TODO add your handling code here:
        String nhapchuoi = nhaptxt.getText().trim();
        chuoihoatxt.setText(chuoihoa(nhapchuoi));
        chuoithuongtxt.setText(chuoithuong(nhapchuoi));
        hoathuongtxt.setText(hoathuong(nhapchuoi));
        sotutxt.setText(soTu(nhapchuoi));
        cacnguyenamtxt.setText(nguyenam(nhapchuoi));
    }//GEN-LAST:event_okbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XuLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XuLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XuLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XuLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XuLi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cacnguyenamtxt;
    private javax.swing.JTextField chuoihoatxt;
    private javax.swing.JTextField chuoithuongtxt;
    private javax.swing.JButton exitbt;
    private javax.swing.JTextField hoathuongtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField nhaptxt;
    private javax.swing.JButton okbt;
    private javax.swing.JButton resetbt;
    private javax.swing.JTextField sotutxt;
    // End of variables declaration//GEN-END:variables
}
