/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package search;

import static search.StudentDB2.search;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import search.Student2;

/**
 *
 * @author OS
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        searchbt = new javax.swing.JButton();
        resetbt = new javax.swing.JButton();
        exitbt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idrd = new javax.swing.JRadioButton();
        namerb = new javax.swing.JRadioButton();
        daterb = new javax.swing.JRadioButton();
        addressrb = new javax.swing.JRadioButton();
        genderrb = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 5));

        jLabel1.setText("Input Information");
        jPanel1.add(jLabel1);
        jPanel1.add(searchtxt);

        searchbt.setText("Search");
        searchbt.setToolTipText("");
        searchbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtActionPerformed(evt);
            }
        });
        jPanel1.add(searchbt);

        resetbt.setText("Reset");
        resetbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtActionPerformed(evt);
            }
        });
        jPanel1.add(resetbt);

        exitbt.setText("Exit");
        exitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtActionPerformed(evt);
            }
        });
        jPanel1.add(exitbt);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 6));

        jLabel2.setText("Search as");
        jPanel2.add(jLabel2);

        buttonGroup1.add(idrd);
        idrd.setText("ID");
        jPanel2.add(idrd);

        buttonGroup1.add(namerb);
        namerb.setText("Name");
        jPanel2.add(namerb);

        buttonGroup1.add(daterb);
        daterb.setText("Date");
        jPanel2.add(daterb);

        buttonGroup1.add(addressrb);
        addressrb.setText("Address");
        jPanel2.add(addressrb);

        buttonGroup1.add(genderrb);
        genderrb.setText("Gender");
        jPanel2.add(genderrb);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Dob", "Address", "Gender"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void showtable(JTable a,Vector<Student2> list) {
        DefaultTableModel model = (DefaultTableModel) a.getModel();
        model.setRowCount(0);
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getDob();
            row[3] = list.get(i).getAddress();
            row[4] = list.get(i).getGender();
            model.addRow(row);
        }
    }
    private void searchbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtActionPerformed
        // TODO add your handling code here:
        String sql = searchtxt.getText();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        try {
            if (idrd.isSelected()) {
                Vector<Student2> kq1 = search(p -> ((Student2) p).getId() == Integer.parseInt(sql));
                showtable(jTable1, kq1);
            } else if (namerb.isSelected()) {
                Vector<Student2> kq2 = search(p -> ((Student2) p).getName().contains(sql));
                showtable(jTable1, kq2);
            } else if (addressrb.isSelected()) {
                Vector<Student2> kq3 = search(p -> ((Student2) p).getAddress().contains(sql));
                showtable(jTable1, kq3);     
            } else if (genderrb.isSelected()) {
                Vector<Student2> kq4 = search(p -> ((Student2) p).getGender().contains(sql));
                showtable(jTable1, kq4);
            } else {
                Vector<Student2> kq5 = search(p -> formatter.format(((Student2) p).getDob()).contains(sql));
                showtable(jTable1, kq5);
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_searchbtActionPerformed

    private void exitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbtActionPerformed

    private void resetbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtActionPerformed
        // TODO add your handling code here:
        searchtxt.setText("");
        Vector<Student2> kq=new Vector<>();
        showtable(jTable1, kq);
    }//GEN-LAST:event_resetbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addressrb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton daterb;
    private javax.swing.JButton exitbt;
    private javax.swing.JRadioButton genderrb;
    private javax.swing.JRadioButton idrd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton namerb;
    private javax.swing.JButton resetbt;
    private javax.swing.JButton searchbt;
    private javax.swing.JTextField searchtxt;
    // End of variables declaration//GEN-END:variables
}
